# This file is a template, and might need editing before it works on your project.
image: uogsoe/soe-php-apache:7.2-ci

stages:
  - test
  - build

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:5.7
  - name: docker:dind
    command: ["--insecure-registry=versions.eng.gla.ac.uk:5555"]

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  # - vendor/
  # - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:

  # Copy over testing configuration.
  # Don't forget to set the database config in .env.testing correctly
  # DB_HOST=mysql
  # DB_DATABASE=project_name
  # DB_USERNAME=root
  # DB_PASSWORD=secret
  - cp .env.gitlab .env

  # Install Composer and project dependencies.
  - composer install

  # If you need Node.js
  #- curl -sL https://deb.nodesource.com/setup_8.x | bash -
  #- apt-get install -y nodejs
  #- npm install
  #- npm run dev

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:clear

  # Run database migrations.
  - php artisan migrate:fresh

test:
  script:
  # run laravel tests
  - php vendor/bin/phpunit --coverage-text --colors=never

  # run frontend tests
  # if you have any task for testing frontend
  # set it in your package.json script
  # comment this out if you don't have a frontend test
  # - npm test

build:
  stage: build
  image: docker:stable
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN versions.eng.gla.ac.uk
  script:
  - cp docker/Dockerfile.prod ./Dockerfile
  - docker build -t versions.eng.gla.ac.uk:5555/billy/glasgow_projects .
  - docker build -t versions.eng.gla.ac.uk:5555/billy/glasgow_projects:$CI_COMMIT_SHA .
  - docker push versions.eng.gla.ac.uk:5555/billy/glasgow_projects
  - docker push versions.eng.gla.ac.uk:5555/billy/glasgow_projects:$CI_COMMIT_SHA