# This file is a template, and might need editing before it works on your project.
image: uogsoe/soe-php-apache:7.2-ci

stages:
  - test
  - build

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  # - vendor/
  # - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
test:
  before_script:
  - cp .env.gitlab .env
  - composer install

  # If you need Node.js
  #- curl -sL https://deb.nodesource.com/setup_8.x | bash -
  #- apt-get install -y nodejs
  #- npm install
  #- npm run dev

  - php artisan key:generate
  - php artisan config:clear
  - php artisan migrate:fresh

  script:
  - php vendor/bin/phpunit --coverage-text --colors=never

build:
  stage: build
  image: docker:stable
  script:
  - cp docker/Dockerfile.prod ./Dockerfile
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH .
  - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA .
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH
  - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA