name: glasgow-projects
recipe: laravel
config:
  webroot: public
  php: '7.4'
  cache: 'redis'
services:
  mail:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  mfs:
    service: appserver
    cmd: php artisan migrate:fresh && php artisan db:seed --class=TestDataSeeder
  test:
    service: appserver
    cmd: CI=1 php ./vendor/bin/phpunit
  testf:
    service: appserver
    cmd: CI=1 php ./vendor/bin/phpunit --filter
