version: "3"
services:
  app:
    image: localhost:5000/glasgow-projects-web
    container_name: glasgow-projects-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - mysql
      - mailhog
    networks:
      - proxy
      - private
    expose:
      - "80"
#    volumes:
#      - .:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: glasgowprojects
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      MAIL_HOST: mailhog
      DEFAULT_DISK: images
    deploy:
      replicas: 3
      labels:
        - "traefik.backend=glasgow-projects-web"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:glasgow.ultravixen.elec.gla.ac.uk"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.default.protocol=http"
#        - "traefik.admin.frontend.rule=Host:admin-app.my-awesome-app.org"
#        - "traefik.admin.protocol=https"
#        - "traefik.admin.port=9443"

  scheduler:
    image: localhost:5000/glasgow-projects-web
    container_name: glasgow-projects-scheduler
    depends_on:
      - app
#    volumes:
#      - .:/var/www/html
    deploy:
      labels:
        - "traefik.enable=false"
    networks:
      - private
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: glasgowprojects
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      MAIL_HOST: mailhog

  queue:
    image: localhost:5000/glasgow-projects-web
    container_name: glasgow-projects-queue
    depends_on:
      - app
#    volumes:
#      - .:/var/www/html
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=false"
    networks:
      - private
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: glasgowprojects
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      MAIL_HOST: mailhog

  redis:
    container_name: glasgow-projects-redis
    image: redis:4
    deploy:
      labels:
        - "traefik.enable=false"
    networks:
      - private
#    ports:
#      - 16379:6379
    volumes:
      - redis:/data

  mysql:
    container_name: glasgow-projects-mysql
    image: mysql:5.7
    deploy:
      labels:
        - "traefik.enable=false"
    networks:
      - private
#    ports:
#      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: glasgowprojects
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  mailhog:
    container_name: glasgow-projects-mailhog
    image: mailhog/mailhog
    deploy:
      labels:
        - "traefik.backend=jwnc-mailhog"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:glasgow.ultravixen.elec.gla.ac.uk;PathPrefixStrip:/mailhog"
        - "traefik.enable=true"
        - "traefik.port=8025"
        - "traefik.default.protocol=http"
#    ports:
#      - 18025:8025
    expose:
      - "8025"
    networks:
      - proxy
      - private

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"

networks:
  private:
  proxy:
    external: true
